version: "3"

tasks:
  down:
    desc: "down all app containers"
    cmds:
      - docker compose down --remove-orphans

  sh:
    desc: "run shell in container"
    cmds:
      - docker compose run --service-ports application bash

  tests:
    desc: "run pytest (pass args after '--')"
    cmds:
      - task: down
      - docker compose run application sh -c "sleep 1 && uv run alembic downgrade base && uv run alembic upgrade head && uv run pytest {{.CLI_ARGS}}"
      - task: down

  migration:
    desc: "create alembic migration (pass args after '--')"
    cmds:
      - docker compose run application sh -c "sleep 1 && uv run alembic upgrade head && uv run alembic revision --autogenerate {{.CLI_ARGS}}"
      - task: down

  build:
    desc: "build app docker container"
    cmds:
      - docker compose build application

  lock:
    desc: lock with update
    cmds:
      - uv lock --upgrade

  install:
    desc: "install local dependencies"
    cmds:
      - uv sync --all-extras --no-install-project --frozen

  lint:
    desc: "run linters"
    cmds:
      - uv run ruff format .
      - uv run ruff check . --fix
      - uv run mypy .
